### ISSUE TITLE
Czech language code: CS or CZ?

### ISSUE THREAD

**Issue by Sduibek** [Sduibek/fixtlang#2]
Read this: https://github.com/Sduibek/fixtlang/commit/205a678fbc9c0d5e1801060b208bd081ddf361e4

I am not sure which we should be using for denoting Czech-related commits.

**Comment by Luffier** [comment]
A little late but I would go with CS to follow the ISO 639-1 rules.

**Comment by Sduibek** [comment]
Yeah I mean it's weird, the standard is definitely CS but many (most?) fan-made content I've found was using CZ.
